language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"

install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install .

env:
  - SYN_RANDOM_SEED=1

script:
  nosetests --with-coverage --cover-package=syn

after_success:
  coveralls